# Generated by Django 4.2.6 on 2023-10-26 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='static/img/bmw_def.jpg', upload_to='profile_pics'),
        ),
    ]
